POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "name": "yokokura",
  "email": "yokokura.tatsuya@gmail.com",
  "password": "yujin4434"
}

###

POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "yokokura.tatsuya@gmail.com",
  "password": "yujin4434"
}

###

POST http://localhost:8080/api/auth/activate
Content-Type: application/json

{
  "token": "c4de861e932f4616b7bdbbcdbd5063bc7efaeea1fb2f4607ad1bed2d48ff2aa7"
}

###

POST http://localhost:8080/api/auth/forgot-password
Content-Type: application/json

{
  "email": "yokokura.tatsuya@gmail.com"
}

###

PATCH  http://localhost:8080/api/auth/password-reset
Content-Type: application/json

{
  "token": "bcdd1e1cc8e144e183c9241fc2a12489d07802ba5cfb46f8b7456edc05f675c5",
  "email": "yokokura.tatsuya@gmail.com",
  "password": "yujin4434"
}

###
GET http://localhost:8080/api/users
