POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "name": "kimura",
  "email": "kimura@gmail.com",
  "password": "kimura"
}

###

POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "tanaka@gmail.com",
  "password": "tanaka"
}

###

POST http://localhost:8080/api/auth/activate
Content-Type: application/json

{
  "token": "c4de861e932f4616b7bdbbcdbd5063bc7efaeea1fb2f4607ad1bed2d48ff2aa7"
}

###
GET http://localhost:8080/api/users
