POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "name": "yokokura",
  "email": "yokokura.tatsuya@gmail.com",
  "password": "password"
}

###

POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "tanaka@gmail.com",
  "password": "tanaka"
}

###
GET http://localhost:8080/api/users
